WIP: Metadata apiv2
openshift/kube-compare pull request #108
Opened 2024-09-17 13:38 UTC by nocturnalastro

2024-09-18 16:39 UTC, lack commented
I noticed two things generally, that we should be careful about:
- The first commit has some go module bumps plus some code changes.  Let's try to keep those in separate commits (if not separate PRs when possible)
- Because we have a go module bump, you'll need to run `go work vendor` to update the vendor/ copies of our modules, and then don't forget to `git add vendor/` to get all the changes in the same commit as the go.mod changes.

2024-09-18 16:53 UTC, nocturnalastro commented
> I noticed two things generally, that we should be careful about:
> 
>     * The first commit has some go module bumps plus some code changes.  Let's try to keep those in separate commits (if not separate PRs when possible)
> 
>     * Because we have a go module bump, you'll need to run `go work vendor` to update the vendor/ copies of our modules, and then don't forget to `git add vendor/` to get all the changes in the same commit as the go.mod changes.

I moved them to a separate PR, I was checked the sync and vendor before I started this must have forgotten to clear them.

2024-09-19 10:34 UTC, lack requested changes
Doc only review at first; I think we should use `allOrNoneOf` instead of `allorNoneOf` or the camelCasePolice may start knocking down our doors.

2024-09-19 10:34 UTC, lack commented on docs/reference-config-guide-v2.md
> +  - `allorNoneOf`: Will cause a validation error when one or more but not all templates are matched for optional blocks of templates.
```suggestion
  - `allOrNoneOf`: Will cause a validation error when some but not all of the templates are matched. Use for sets of templates where the entire set is optional, but if at least one is present then all the others must also be present.
```

2024-09-19 10:34 UTC, lack commented on docs/reference-config-guide-v2.md
> +  - `allOf`: Will cause a validation error if not all templates are matched for required templates.
```suggestion
  - `allOf`: Will cause a validation error if not all the templates are matched. Use for sets of required templates.
```

2024-09-19 10:34 UTC, lack commented on docs/reference-config-guide-v2.md
> +  - `anyOf`: Will never cause a vaildation error, for completely optional templates
```suggestion
  - `anyOf`: Will only cause validation errors for the content of matched templates. Use for completely optional templates.
```

2024-09-19 10:34 UTC, lack commented on docs/reference-config-guide-v2.md
> +  - `noneOf`: Will cause a vaildation error if any of the templates are matched useful to exclude CRs
```suggestion
  - `noneOf`: Will cause a validation error if any of the templates are matched. Use for excluding CRs.
```

2024-09-19 10:34 UTC, lack commented on docs/reference-config-guide-v2.md
> +  - `oneOf`: Will cause a vaildation error when None or more than one templates is matched, for when you want to match exactly one template in the block
```suggestion
  - `oneOf`: Will cause a validation error when none or more than one of the templates is matched. For requiring exactly one template in the set.
```

2024-09-19 10:34 UTC, lack commented on docs/reference-config-guide-v2.md
> +  - `anyOneOf`: Will throw a validation error if more than one is matched, for when you optionally want only one of the templates the block
```suggestion
  - `anyOneOf`: Will throw a validation error if more than one template is matched. Use for optionally allowing only one of the templates in the set.
```

2024-09-19 10:34 UTC, lack commented on docs/reference-config-guide-v2.md
> +# requiredTemplates contains all needed reference CRs to comply with ExampleComponent1
I think this comment is wrong now?

2024-09-19 11:41 UTC, lack approved these changes

2024-09-19 11:45 UTC, merged